### ISSUE TITLE
Дополнить «Маяк на раздел»

### ISSUE THREAD

**Issue by dague** [cnord/doc-gsm-devices#5]
## Предыстория

В 11-й версии прошивки появилось новое действие для «Автоматики», оно называется «периодически замыкать и размыкать открытый коллектор». 
Это новое действие делалось под два кейса. 
Первый – взаимодействие со специфической клавиатурой, которой нужны пульсации по входу, чтобы она правильно отображала взятие. Откровенно говоря, я не вникал в детали, просто запомнил, что нужно.
А вот второй – _полноценный_ Маяк на раздел. Дело в том, что полноценный Маяк должен отображать три состояния объекта или раздела: взят под охрану – горит, снят с охраны – не горит, взят под охрану и была тревога – мигает. 
Глобальный маяк, который отображает состояние всего объекта и прекрасно подходит для небольших объектов из одного раздела, так и работает. 
А если на объекте несколько разделов и требуется отображать их состояние по отдельности, то мы предлагаем задействовать для этих целей автоматику: замкнули при взятии раздела, разомкнули при снятии. Но в предыдущей версии нельзя было отобразить тревогу: не было нужного действия автоматики. А теперь оно появилось. 
## Задача

Нужно дополнить [статью на саппорте](http://support.cnord.ru/hc/ru/articles/211099738) – добавить в нее еще одно действие, которое нужно сконфигурировать, чтобы Маяк начинал мигать при тревоге.

![default](https://cloud.githubusercontent.com/assets/1608702/13596518/f78f1f0a-e523-11e5-901b-38f5392525fd.png)

Включать мигание, если событие с указанным кодом по разделу, для которого ставим Маяк.

Нужно не забыть дополнить почти все разделы статьи: задача, версии и т.д.

Нужно не забыть написать, что если один шлейф принадлежит разным разделам, то тревога по шлейфу будет сформирована по разделу с наименьшим номером.

Нужно не забыть написать, что в Норде GSM три типа охранных шлейфов, которые имеют два кода события: Охранный / Проходной – E130, Охранный без сирены – E146. Если в разделе есть оба кода, то действия для включения мигания должно быть тоже два.
## Полезные ссылки

[Хаббл версии 7.12](https://yadi.sk/d/FCEQhwWepyetJ) – есть настройка нового действия, можно использовать эту версию конфигуратора для обновленных скриншотов.

**Comment by nattashikk** [comment]
not relevant
